### ISSUE TITLE
Hitbloq not shown nor not working..

### ISSUE THREAD

**Issue by AndrewTheWolfdog** [PauseChampions/Hitbloq#13]
I have a problem, I have score saber, Beat Saber Markup Language, and Sira Util mod installed as a latest version along with Leaderboard Core installed which I got hitbloq installed. When I open the game, hitbloq doesn't appear on the leaderboards nor it's not working. I uninstalled and reinstalled a few times and it doesn't work. Any idea?

**Comment by rithik-b** [comment]
I’ll try to make it more clear in the next release but here’s what you can do for now
Hitbloq will only appear if you have a hitbloq ranked map selected. You can use the MorePlaylists mod on ModAssistant and click on “Source” then click “Hitbloq” to browse Hitbloq map pools. Simply download all songs from one of the playlists and open one of the songs to see Hitbloq!
