### ISSUE TITLE
Add Ui to browse/download hitbloq playlists

### ISSUE THREAD

**Issue by LackWiz** [PauseChampions/Hitbloq#15]
Or add a button that links to the hitbloq pools website. Most players don't know how to get hitbloq playlists or how to get started

**Comment by rithik-b** [comment]
The current release had a ModList description with all relevant links... but ModList wasn't released soon as planned.
An ingame pool leaderboard browser is planned which would also have the download button there

**Comment by rithik-b** [comment]
Added in latest release!
