### ISSUE TITLE
HitBloq Leaderboard does not hide when you view a WIP level, shows scores of previously selected level

### ISSUE THREAD

**Issue by ModdingPink** [PauseChampions/Hitbloq#22]
<img width="635" alt="image" src="https://github.com/PauseChampions/Hitbloq/assets/62712899/89e11f21-b1d0-4eab-9023-4fecfb577e5c">

<img width="644" alt="image" src="https://github.com/PauseChampions/Hitbloq/assets/62712899/b085a07f-fda6-4288-be17-93fe12afcc21">

**Comment by Sirspam** [comment]
Fixed in e670ad1f39df93042faee87617e8558c7e0740e2
